### ISSUE TITLE
Just a few changes

### ISSUE THREAD

**Issue by virajp691** [RyanEder/clearParquet#11]
### Shadow Declaration warning 
In `core/ParquetSchema.hpp` the constructor param `type` and the enum `type` shadow each other.  Suggest renaming the enum to NodeType.
```
clearParquet/core/ParquetSchema.hpp:25:9: error: declaration of ‘type’ shadows a member of ‘clearParquet::Node’ [-Werror=shadow]
         : _type(type), _name(name), _repetition(repetition), _convertedType(convertedType), _id(id), _parent(nullptr) {
         ^
In file included from clearParquet/core/ParquetFileWriter.hpp:16,
                 from clearParquet/core/ParquetStreamWriter.hpp:2,
                 from clearParquet/test/writer.cpp:8:
clearParquet/core/ParquetSchema.hpp:22:10: note: shadowed declaration is here
     enum type { PRIMITIVE, GROUP };
``` 
### Extra Const qualifer that gets ignored
In `core/ParquetTypes.hpp` the function `__is_set()` has an extra const qualifer prefix, I think you can safely remove it.
```
before - const bool __is_set() const {
after - bool __is_set() const {
```
### Builder Pattern
In `core/ParquetWriterProperties.hpp` the compression() function does not return a reference to the current builder.
Update the function decleration to `Builder& compression(Compression::type compression)` and return a `*this`.
### No RTTI 
Don't quote me on this, but I believe apache::arrow does not use dynamic casting so if possible to remove the dynamic casts in `core/ParquetSchema.hpp` would be great. 
### Expose some stream properties
`GetNumRows()`
`GetOffset()` I think this is `Tell()` in apache arrow, but basically how many bytes are currently part of the file (post compression) I imagine.

**Comment by RyanEder** [comment]
This should all be included in the latest main. Feel free to close if up to par.
